steps:
  - id: Run CI Tests
    name: 'gcr.io/${PROJECT_ID}/docker-compose'
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'COMMIT_SHA=${COMMIT_SHA}'
    entrypoint: 'bash'
    args: ['./bin/ci.sh']
    timeout: 1200s
  - id: Get our secret environment variables
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'gcloud secrets versions access ${APP_SECRETS} >> .env.prod']
  - id: Convert prod secrets into JSON for terraform
    name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm i -g dotenv-to-json
        cat .env.prod | dotenv-to-json >> .env.prod.tfvars.json
  - id: tf init
    name: 'hashicorp/terraform:${_TF_VERSION}'
    args: ['init', '-input=false', './terraform/prod/']
  - id: tf plan
    name: 'hashicorp/terraform:${_TF_VERSION}'
    args: ['plan', '-input=false', '-var-file=.env.prod.tfvars.json', '-out=plan.tfplan', './terraform/prod/']

substitutions:
  _TF_VERSION: 0.13.3

options:
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'COMMIT_SHA=$COMMIT_SHA'
    - 'TF_IN_AUTOMATION=true'
    - 'TF_VAR_commit_sha=$COMMIT_SHA'
    - 'CI=true'

timeout: 10000s
